const cards = [
  {
    id: 'fabric',
    company: 'Fabric.inc',
    period: 'Aug 2020  - Sep 2022',
    title: 'Software Development Engineer',
    location: 'Remote',
    what: 'Doing',
    tasks: ['Headless CMS Development'],
    techStack: [
      'React',
      'TypeScript',
      'Nextjs',
      'Nodejs',
      'Jest',
      'GraphQL',
      'Git',
    ],
  },
  {
    id: 'bell',
    company: 'Bell Canada',
    period: 'July 2018 - June 2020',
    title: 'Web Application Developer',
    location: 'Montreal',
    what: 'Building',
    tasks: ['Lots of Web Apps'],
    techStack: [
      'React',
      'AngularJS',
      'Javascript',
      'HTML5',
      'CSS3',
      'Less',
      'SVN',
    ],
  },
  {
    id: 'cgi',
    company: 'CGI',
    period: 'Apr 2018 - June 2018',
    title: 'Front-end Developer',
    location: 'Montreal',
    what: 'Doing',
    tasks: ['Enhancement', 'Bug fix', 'HTML Email'],
    techStack: ['AngularJS', 'JavaScript', 'HTML5', 'CSS3', 'Less', 'Git'],
  },
  {
    id: 'reitmans',
    company: 'Reitmans',
    period: 'Feb 2016 - Mar 2018',
    title: 'Front-end Integrator',
    location: 'Montreal',
    what: 'Doing',
    tasks: ['Markup', 'Style', 'HTML Email', 'DOM Manipulation'],
    techStack: ['HTML5', 'CSS3', 'Sass', 'Susy', 'JavaScript', 'SVN'],
  },
  {
    id: 'jfandsons',
    company: 'JF and Sons',
    period: 'Jan 2015  - Dec 2015',
    title: 'Designer/Integrator',
    location: 'Montreal',
    what: 'Doing',
    tasks: ['Design', 'Markup', 'HTML Email'],
    techStack: [
      'HTML5',
      'CSS3',
      'Sass',
      'JavaScript',
      'PHP',
      'Photoshop',
      'Illustrator',
      'Git',
    ],
  },
]

export default cards
