# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: daishodesign CI

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Make envfile
        run: |
          cat << EOF > .env
          NODE_ENV=${{secrets.NODE_ENV}}
          PORT=${{secrets.PORT}}
          MAIL_USER=${{secrets.MAIL_USER}}
          MAIL_PASS=${{secrets.MAIL_PASS}}
          MAIL_HOST=${{secrets.MAIL_HOST}}
          MAIL_PORT=${{secrets.MAIL_PORT}}
          MAIL_DESTINATION=${{secrets.MAIL_DESTINATION}}
          RECAPTCHA_SECRET_KEY=${{secrets.RECAPTCHA_SECRET_KEY}}
          EOF

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      # - run: pm2 start --name daishodesign src/server/server.js --watch # for the initial deployment
      - run: pm2 restart daishodesign # for continuous deployment

